# BSD-3-Clause License - see LICENSE file

# --------------------------------------------------
# site metadata
# --------------------------------------------------
site_name: flow_theory
site_url: https://uahypersonics.github.io/flow-theory
site_author: Christoph Hader
site_description: Theoretical estimates for high-speed aerodynamics.

# --------------------------------------------------
# github repository
# --------------------------------------------------
repo_name: uahypersonics/flow-theory
repo_url: https://github.com/uahypersonics/flow-theory
edit_uri: edit/main/docs/

# --------------------------------------------------
# theme
# --------------------------------------------------
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

# --------------------------------------------------
# navigation
# --------------------------------------------------
nav:
  - Home: index.md
  - Installation: installation.md

# --------------------------------------------------
# plugins
# --------------------------------------------------
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
