"""Configuration adapter for the [transition] workflow section."""

# --------------------------------------------------
# load necessary modules
# --------------------------------------------------
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .schema import ConfigNode, validate_section_keys

# --------------------------------------------------
# section structure
# --------------------------------------------------
_ALLOWED_KEYS = {"mach", "method", "output", "re1", "run", "tw_te"}
_REQUIRED_KEYS = {"mach", "re1", "tw_te"}
_VALID_METHODS = {"van_driest_blumer"}


# --------------------------------------------------
# typed configuration
# --------------------------------------------------
@dataclass(slots=True, frozen=True)
class TransitionConfig:
    """Validated inputs for a transition-location calculation."""

    mach: object
    re1: object
    tw_te: object
    run: bool = True
    method: str = "van_driest_blumer"
    output: Path | None = None

    def __post_init__(self) -> None:
        """Normalize and validate transition options."""

        # normalize the transition criterion name
        method_value = self.method.strip().lower()
        object.__setattr__(self, "method", method_value)

        # validate the selected transition criterion
        if method_value not in _VALID_METHODS:
            raise ValueError(
                f"[transition] method must be one of {sorted(_VALID_METHODS)}"
            )


# --------------------------------------------------
# public API
# --------------------------------------------------
def parse_transition_config(section: ConfigNode) -> TransitionConfig:
    """Validate and convert a [transition] section."""

    # validate section keys before reading values
    validate_section_keys(
        section,
        section_name="transition",
        allowed_keys=_ALLOWED_KEYS,
        required_keys=_REQUIRED_KEYS,
    )

    # retain compatibility with configs generated by the former global workflow
    run_value = getattr(section, "run", True)
    if not isinstance(run_value, bool):
        raise ValueError("transition.run must be true or false")

    # convert optional values
    method = str(getattr(section, "method", "van_driest_blumer"))
    output_value = getattr(section, "output", None)
    output = None if output_value is None else Path(str(output_value))

    # build the typed runner input
    config = TransitionConfig(
        mach=section.mach,
        re1=section.re1,
        tw_te=section.tw_te,
        run=run_value,
        method=method,
        output=output,
    )

    return config
